### PR TITLE
Fix return value for RVO

### PR DESCRIPTION
**Pull request by forno**
Optimize return value with RVO.

You should not use std::move to return value.
(except on ownership transfering)

Refarence:
- https://qiita.com/zhupeijun/items/b8f7fe3bd604192a0b0c

Licence:
I add unlicense to this change.
You can continue Apache license 2.0(your license) without special notice.
But, I would be grateful if you could add me to contributors.

### CODE REVIEW

**Comment by forno** [comment]
Sorry I got mistake.
RVO effect to only rvalue.

I'm sorry for confusing you.

**Comment by forno** [comment]
It is rvalue.
ss.str();

**Comment by eiennohito** [comment]
Could you please redo this pull request to the `master` branch.
I will remove legacy jumanpp sources (the current src dir) from `v2` very soon.

**Comment by forno** [comment]
I see.
I resend this change soon.

Thank you.

**Comment by eiennohito** [comment]
One more consideration: I will not really support the legacy juman++ anymore.
It is 25x slower with RNN and ~50x slower without RNN and even has lower accuracy than the current state of `v2`.

**Pull request closed without merging**
