### PR TITLE
Bug fix and add additional instruction for Ubuntu22.04 installation

### PR DESCRIPTION
**Pull request by sagatake**
references (related to my several commits within few minutes):
- (libraries for Ubuntu22.04) https://github.com/Tencent/ncnn/issues/1342
- (set size of array with static value) https://src.fedoraproject.org/rpms/catch1/blob/rawhide/f/catch1-sigstksz.patch
- (add additional include delaration) https://github.com/onnx/onnx-tensorrt/issues/474

### CODE REVIEW

**Comment by eiennohito** [comment]
Fixes #150

**Comment by sagatake** [comment]
Special thanks to https://twitter.com/hmtd223/status/1553353904791818240?s=20

**Comment by eiennohito** [comment]
Thank you very much!

**Comment by ArthurZucker** [comment]
Thanks! For anyone building a docker, this fixes 
```bash
6.462 In file included from /usr/include/signal.h:328,
6.462                  from /jumanpp-2.0.0-rc3/libs/catch.hpp:6429,
6.462                  from /jumanpp-2.0.0-rc3/src/testing/catch_main.cc:6:
6.462 /jumanpp-2.0.0-rc3/libs/catch.hpp:6604:45: error: size of array ‘altStackMem’ is not an integral constant-expression
6.462  6604 |     char FatalConditionHandler::altStackMem[SIGSTKSZ] = {};
6.462       |                                             ^~~~~~~~
7.429 make[2]: *** [src/testing/CMakeFiles/jpp_test_catch_main_lib.dir/build.make:76: src/testing/CMakeFiles/jpp_test_catch_main_lib.dir/catch_main.cc.o] Error 1
7.429 make[1]: *** [CMakeFiles/Makefile2:615: src/testing/CMakeFiles/jpp_test_catch_main_lib.dir/all] Error 2
7.430 make: *** [Makefile:146: all] Error 2
```
the `altStackMem[SIGSTKSZ]` error -> either use `rc4` or downgrade glib g++ etc

**Pull request merged**
