### PR TITLE
Use CMake to get Eigen dependency

### PR DESCRIPTION
**Pull request by DoumanAsh**
I guess it is up to you, but personally I find python more windows-friendly than having to use bash on windows.

### CODE REVIEW

**Comment by eiennohito** [comment]
I think it would be better to have a CMake-only solution...
Cmake can even compress/decompress stuff by itself https://stackoverflow.com/questions/7050997/zip-files-using-cmake

**Comment by DoumanAsh** [comment]
Ok

**Comment by DoumanAsh** [comment]
I'll make eigen a CMake dependency then so that it will be downloaded only for dependencies it is needed

**Comment by DoumanAsh** [comment]
It is a bit hacky, but it seems we cannot depend on artifacts produced by `ExternalProject` so I made dummy interface library that exports headers.

**Comment by eiennohito** [comment]
Ah, I forgot one thing.
The only other thing I really want to do is to package Eigen with releases (they should not download anything from the internet and require an internet connection to work).

I'll look into how that is possible to implement with your patch.

**Comment by DoumanAsh** [comment]
I'm not really understand this specification... Should we just put eigen into repo?

**Comment by eiennohito** [comment]
I think that download is OK for the git version (and even skip download if Eigen was already present, e.g. some other project using J++V2 would have its own Eigen and would like to use it instead) and should be left this way, but it would be nicer to put Eigen in package versions (which package trained models as well).

**Comment by eiennohito** [comment]
I'll do this thing myself (at least bundling), so don't really think deeply about this.
I'll merge the PR later today.

**Comment by DoumanAsh** [comment]
Ok, thank you, then I guess I should close this PR.

**Comment by eiennohito** [comment]
I wanted to build on top of your work...

**Comment by eiennohito** [comment]
So don't delete your branch yet pls. :p

**Comment by DoumanAsh** [comment]
Oh... Ok, My branch will remain, no worries.

**Comment by eiennohito** [comment]
I have made changes so the Eigen would be downloaded by CMake.
Also I wanted to setup a CI on in-lab infrasturcture, but we have only one Windows 2012 (non R2) machine and VS2017 does not support it. MSYS build should work though.

**Comment by eiennohito** [comment]
The VS2015.3 installation has failed as well... :|
Windows is out of luck

**Comment by DoumanAsh** [comment]
@eiennohito Would it be ok to at least setup appveyor to verify builds ? I can prepare config.

**Comment by eiennohito** [comment]
Yes, definitely!

**Comment by eiennohito** [comment]
BTW, I found a machine I can preparate, so I will upgrade it to Win10 and use as a win build slave.

**Comment by DoumanAsh** [comment]
Ok I'll prepare appveyor config on this weekend(will need to read their docs as I didn't use it for C++, yes surprisingly :))

**Pull request closed without merging**
